// This file is automatically generated. Do not edit it directly.
import type { Database } from './types';
export type { Database };

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export { supabase } from "@/lib/supabase";
